services:
  client:
    build: ./client
    container_name: client
    ports:
      - "3000:5173"
  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_NAME}
    volumes:
      - mongo:/data/db
    ports:
      - "6000:27017"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
volumes:
  mongo:
  redis:
